<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Understand your dataset with Xgboost • xgboost</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Understand your dataset with Xgboost">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">xgboost</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.90.0.2</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa fas fa-archive fa-lg"></span>
     
    R Packages
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../../boot/index.html">boot</a>
    </li>
    <li>
      <a href="../../broom/index.html">broom</a>
    </li>
    <li>
      <a href="../../caret/index.html">caret</a>
    </li>
    <li>
      <a href="../../cluster/index.html">cluster</a>
    </li>
    <li>
      <a href="../../coefplot/index.html">coefplot</a>
    </li>
    <li>
      <a href="../../data.table/index.html">data.table</a>
    </li>
    <li>
      <a href="../../devtools/index.html">devtools</a>
    </li>
    <li>
      <a href="../../dplyr/index.html">dplyr</a>
    </li>
    <li>
      <a href="../../e1071/index.html">e1071</a>
    </li>
    <li>
      <a href="../../forcats/index.html">forcats</a>
    </li>
    <li>
      <a href="../../gbm/index.html">gbm</a>
    </li>
    <li>
      <a href="../../ggplot2/index.html">ggplot2</a>
    </li>
    <li>
      <a href="../../glmnet/index.html">glmnet</a>
    </li>
    <li>
      <a href="../../gridExtra/index.html">gridExtra</a>
    </li>
    <li>
      <a href="../../ISLR/index.html">ISLR</a>
    </li>
    <li>
      <a href="../../MASS/index.html">MASS</a>
    </li>
    <li>
      <a href="../../pdp/index.html">pdp</a>
    </li>
    <li>
      <a href="../../pls/index.html">pls</a>
    </li>
    <li>
      <a href="../../plyr/index.html">plyr</a>
    </li>
    <li>
      <a href="../../pROC/index.html">pROC</a>
    </li>
    <li>
      <a href="../../purrr/index.html">purrr</a>
    </li>
    <li>
      <a href="../../randomForest/index.html">randomForest</a>
    </li>
    <li>
      <a href="../../readr/index.html">readr</a>
    </li>
    <li>
      <a href="../../rpart/index.html">rpart</a>
    </li>
    <li>
      <a href="../../rpart.plot/index.html">rpart.plot</a>
    </li>
    <li>
      <a href="../../stringr/index.html">stringr</a>
    </li>
    <li>
      <a href="../../tibble/index.html">tibble</a>
    </li>
    <li>
      <a href="../../tidyr/index.html">tidyr</a>
    </li>
    <li>
      <a href="../../xgboost/index.html">xgboost</a>
    </li>
  </ul>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/discoverYourData.html">Understand your dataset with Xgboost</a>
    </li>
    <li>
      <a href="../articles/xgboostPresentation.html">Xgboost presentation</a>
    </li>
    <li>
      <a href="../articles/xgboostfromJSON.html">XGBoost from JSON</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/dmlc/xgboost">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Understand your dataset with Xgboost</h1>
                        <h4 class="author">Tianqi Chen, Tong He, Michaël Benesty, Yuan Tang</h4>
            
      
      <small class="dont-index">Source: <a href="https://github.com/dmlc/xgboost/blob/master/../../vignettes/discoverYourData.Rmd"><code>../../vignettes/discoverYourData.Rmd</code></a></small>
      <div class="hidden name"><code>discoverYourData.Rmd</code></div>

    </div>

    
    
<div id="understand-your-dataset-with-xgboost" class="section level1">
<h1 class="hasAnchor">
<a href="#understand-your-dataset-with-xgboost" class="anchor"></a>Understand your dataset with XGBoost</h1>
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>The purpose of this vignette is to show you how to use <strong>Xgboost</strong> to discover and understand your own dataset better.</p>
<p>This vignette is not about predicting anything (see <a href="https://github.com/dmlc/xgboost/blob/master/R-package/vignettes/xgboostPresentation.Rmd">Xgboost presentation</a>). We will explain how to use <strong>Xgboost</strong> to highlight the <em>link</em> between the <em>features</em> of your data and the <em>outcome</em>.</p>
<p>Package loading:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span>(xgboost)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span>(Matrix)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span>(data.table)</a>
<a class="sourceLine" id="cb1-4" data-line-number="4"><span class="cf">if</span> (<span class="op">!</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span>(<span class="st">'vcd'</span>)) <span class="kw"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span>(<span class="st">'vcd'</span>)</a></code></pre></div>
<blockquote>
<p><strong>VCD</strong> package is used for one of its embedded dataset only.</p>
</blockquote>
</div>
<div id="preparation-of-the-dataset" class="section level2">
<h2 class="hasAnchor">
<a href="#preparation-of-the-dataset" class="anchor"></a>Preparation of the dataset</h2>
<div id="numeric-v-s--categorical-variables" class="section level3">
<h3 class="hasAnchor">
<a href="#numeric-v-s--categorical-variables" class="anchor"></a>Numeric v.s. categorical variables</h3>
<p><strong>Xgboost</strong> manages only <code>numeric</code> vectors.</p>
<p>What to do when you have <em>categorical</em> data?</p>
<p>A <em>categorical</em> variable has a fixed number of different values. For instance, if a variable called <em>Colour</em> can have only one of these three values, <em>red</em>, <em>blue</em> or <em>green</em>, then <em>Colour</em> is a <em>categorical</em> variable.</p>
<blockquote>
<p>In <strong>R</strong>, a <em>categorical</em> variable is called <code>factor</code>.</p>
<p>Type <code><a href="https://rdrr.io/r/base/factor.html">?factor</a></code> in the console for more information.</p>
</blockquote>
<p>To answer the question above we will convert <em>categorical</em> variables to <code>numeric</code> one.</p>
</div>
<div id="conversion-from-categorical-to-numeric-variables" class="section level3">
<h3 class="hasAnchor">
<a href="#conversion-from-categorical-to-numeric-variables" class="anchor"></a>Conversion from categorical to numeric variables</h3>
<div id="looking-at-the-raw-data" class="section level4">
<h4 class="hasAnchor">
<a href="#looking-at-the-raw-data" class="anchor"></a>Looking at the raw data</h4>
<p>In this Vignette we will see how to transform a <em>dense</em> <code>data.frame</code> (<em>dense</em> = few zeroes in the matrix) with <em>categorical</em> variables to a very <em>sparse</em> matrix (<em>sparse</em> = lots of zero in the matrix) of <code>numeric</code> features.</p>
<p>The method we are going to see is usually called <a href="http://en.wikipedia.org/wiki/One-hot">one-hot encoding</a>.</p>
<p>The first step is to load <code>Arthritis</code> dataset in memory and wrap it with <code>data.table</code> package.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(Arthritis)</a>
<a class="sourceLine" id="cb2-2" data-line-number="2">df &lt;-<span class="st"> </span><span class="kw"><a href="https://Rdatatable.gitlab.io/data.table/reference/data.table.html">data.table</a></span>(Arthritis, <span class="dt">keep.rownames =</span> F)</a></code></pre></div>
<blockquote>
<p><code>data.table</code> is 100% compliant with <strong>R</strong> <code>data.frame</code> but its syntax is more consistent and its performance for large dataset is <a href="http://stackoverflow.com/questions/21435339/data-table-vs-dplyr-can-one-do-something-well-the-other-cant-or-does-poorly">best in class</a> (<code>dplyr</code> from <strong>R</strong> and <code>Pandas</code> from <strong>Python</strong> <a href="https://github.com/Rdatatable/data.table/wiki/Benchmarks-%3A-Grouping">included</a>). Some parts of <strong>Xgboost</strong> <strong>R</strong> package use <code>data.table</code>.</p>
</blockquote>
<p>The first thing we want to do is to have a look to the first few lines of the <code>data.table</code>:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(df)</a></code></pre></div>
<pre><code>##    ID Treatment  Sex Age Improved
## 1: 57   Treated Male  27     Some
## 2: 46   Treated Male  29     None
## 3: 77   Treated Male  30     None
## 4: 17   Treated Male  32   Marked
## 5: 36   Treated Male  46   Marked
## 6: 23   Treated Male  58   Marked</code></pre>
<p>Now we will check the format of each column.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/utils/str.html">str</a></span>(df)</a></code></pre></div>
<pre><code>## Classes 'data.table' and 'data.frame':   84 obs. of  5 variables:
##  $ ID       : int  57 46 77 17 36 23 75 39 33 55 ...
##  $ Treatment: Factor w/ 2 levels "Placebo","Treated": 2 2 2 2 2 2 2 2 2 2 ...
##  $ Sex      : Factor w/ 2 levels "Female","Male": 2 2 2 2 2 2 2 2 2 2 ...
##  $ Age      : int  27 29 30 32 46 58 59 59 63 63 ...
##  $ Improved : Ord.factor w/ 3 levels "None"&lt;"Some"&lt;..: 2 1 1 3 3 3 1 3 1 1 ...
##  - attr(*, ".internal.selfref")=&lt;externalptr&gt;</code></pre>
<p>2 columns have <code>factor</code> type, one has <code>ordinal</code> type.</p>
<blockquote>
<p><code>ordinal</code> variable :</p>
<ul>
<li>can take a limited number of values (like <code>factor</code>) ;</li>
<li>these values are ordered (unlike <code>factor</code>). Here these ordered values are: <code>Marked &gt; Some &gt; None</code>
</li>
</ul>
</blockquote>
</div>
<div id="creation-of-new-features-based-on-old-ones" class="section level4">
<h4 class="hasAnchor">
<a href="#creation-of-new-features-based-on-old-ones" class="anchor"></a>Creation of new features based on old ones</h4>
<p>We will add some new <em>categorical</em> features to see if it helps.</p>
<div id="grouping-per-10-years" class="section level5">
<h5 class="hasAnchor">
<a href="#grouping-per-10-years" class="anchor"></a>Grouping per 10 years</h5>
<p>For the first feature we create groups of age by rounding the real age.</p>
<p>Note that we transform it to <code>factor</code> so the algorithm treat these age groups as independent values.</p>
<p>Therefore, 20 is not closer to 30 than 60. To make it short, the distance between ages is lost in this transformation.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(df[,AgeDiscret <span class="op">:</span><span class="er">=</span><span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/Round.html">round</a></span>(Age<span class="op">/</span><span class="dv">10</span>,<span class="dv">0</span>))])</a></code></pre></div>
<pre><code>##    ID Treatment  Sex Age Improved AgeDiscret
## 1: 57   Treated Male  27     Some          3
## 2: 46   Treated Male  29     None          3
## 3: 77   Treated Male  30     None          3
## 4: 17   Treated Male  32   Marked          3
## 5: 36   Treated Male  46   Marked          5
## 6: 23   Treated Male  58   Marked          6</code></pre>
</div>
<div id="random-split-into-two-groups" class="section level5">
<h5 class="hasAnchor">
<a href="#random-split-into-two-groups" class="anchor"></a>Random split into two groups</h5>
<p>Following is an even stronger simplification of the real age with an arbitrary split at 30 years old. We choose this value <strong>based on nothing</strong>. We will see later if simplifying the information based on arbitrary values is a good strategy (you may already have an idea of how well it will work…).</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(df[,AgeCat<span class="op">:</span><span class="er">=</span><span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span>(<span class="kw"><a href="https://Rdatatable.gitlab.io/data.table/reference/fifelse.html">ifelse</a></span>(Age <span class="op">&gt;</span><span class="st"> </span><span class="dv">30</span>, <span class="st">"Old"</span>, <span class="st">"Young"</span>))])</a></code></pre></div>
<pre><code>##    ID Treatment  Sex Age Improved AgeDiscret AgeCat
## 1: 57   Treated Male  27     Some          3  Young
## 2: 46   Treated Male  29     None          3  Young
## 3: 77   Treated Male  30     None          3  Young
## 4: 17   Treated Male  32   Marked          3    Old
## 5: 36   Treated Male  46   Marked          5    Old
## 6: 23   Treated Male  58   Marked          6    Old</code></pre>
</div>
<div id="risks-in-adding-correlated-features" class="section level5">
<h5 class="hasAnchor">
<a href="#risks-in-adding-correlated-features" class="anchor"></a>Risks in adding correlated features</h5>
<p>These new features are highly correlated to the <code>Age</code> feature because they are simple transformations of this feature.</p>
<p>For many machine learning algorithms, using correlated features is not a good idea. It may sometimes make prediction less accurate, and most of the time make interpretation of the model almost impossible. GLM, for instance, assumes that the features are uncorrelated.</p>
<p>Fortunately, decision tree algorithms (including boosted trees) are very robust to these features. Therefore we have nothing to do to manage this situation.</p>
</div>
<div id="cleaning-data" class="section level5">
<h5 class="hasAnchor">
<a href="#cleaning-data" class="anchor"></a>Cleaning data</h5>
<p>We remove ID as there is nothing to learn from this feature (it would just add some noise).</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">df[,ID<span class="op">:</span><span class="er">=</span><span class="ot">NULL</span>]</a></code></pre></div>
<p>We will list the different values for the column <code>Treatment</code>:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/levels.html">levels</a></span>(df[,Treatment])</a></code></pre></div>
<pre><code>## [1] "Placebo" "Treated"</code></pre>
</div>
</div>
<div id="encoding-categorical-features" class="section level4">
<h4 class="hasAnchor">
<a href="#encoding-categorical-features" class="anchor"></a>Encoding categorical features</h4>
<p>Next step, we will transform the categorical data to dummy variables. Several encoding methods exist, e.g., <a href="http://en.wikipedia.org/wiki/One-hot">one-hot encoding</a> is a common approach. We will use the <a href="http://www.ats.ucla.edu/stat/r/library/contrast_coding.htm#dummy">dummy contrast coding</a> which is popular because it produces “full rank” encoding (also see <a href="http://appliedpredictivemodeling.com/blog/2013/10/23/the-basics-of-encoding-categorical-data-for-predictive-models">this blog post by Max Kuhn</a>).</p>
<p>The purpose is to transform each value of each <em>categorical</em> feature into a <em>binary</em> feature <code>{0, 1}</code>.</p>
<p>For example, the column <code>Treatment</code> will be replaced by two columns, <code>TreatmentPlacebo</code>, and <code>TreatmentTreated</code>. Each of them will be <em>binary</em>. Therefore, an observation which has the value <code>Placebo</code> in column <code>Treatment</code> before the transformation will have after the transformation the value <code>1</code> in the new column <code>TreatmentPlacebo</code> and the value <code>0</code> in the new column <code>TreatmentTreated</code>. The column <code>TreatmentPlacebo</code> will disappear during the contrast encoding, as it would be absorbed into a common constant intercept column.</p>
<p>Column <code>Improved</code> is excluded because it will be our <code>label</code> column, the one we want to predict.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1">sparse_matrix &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/pkg/Matrix/man/sparse.model.matrix.html">sparse.model.matrix</a></span>(Improved <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> df)[,<span class="op">-</span><span class="dv">1</span>]</a>
<a class="sourceLine" id="cb14-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(sparse_matrix)</a></code></pre></div>
<pre><code>## 6 x 9 sparse Matrix of class "dgCMatrix"
##   TreatmentTreated SexMale Age AgeDiscret3 AgeDiscret4 AgeDiscret5 AgeDiscret6
## 1                1       1  27           1           .           .           .
## 2                1       1  29           1           .           .           .
## 3                1       1  30           1           .           .           .
## 4                1       1  32           1           .           .           .
## 5                1       1  46           .           .           1           .
## 6                1       1  58           .           .           .           1
##   AgeDiscret7 AgeCatYoung
## 1           .           1
## 2           .           1
## 3           .           1
## 4           .           .
## 5           .           .
## 6           .           .</code></pre>
<blockquote>
<p>Formula <code>Improved ~ .</code> used above means transform all <em>categorical</em> features but column <code>Improved</code> to binary values. The <code>-1</code> column selection removes the intercept column which is full of <code>1</code> (this column is generated by the conversion). For more information, you can type <code><a href="https://rdrr.io/pkg/Matrix/man/sparse.model.matrix.html">?sparse.model.matrix</a></code> in the console.</p>
</blockquote>
<p>Create the output <code>numeric</code> vector (not as a sparse <code>Matrix</code>):</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">output_vector =<span class="st"> </span>df[,Improved] <span class="op">==</span><span class="st"> "Marked"</span></a></code></pre></div>
<ol style="list-style-type: decimal">
<li>set <code>Y</code> vector to <code>0</code>;</li>
<li>set <code>Y</code> to <code>1</code> for rows where <code>Improved == Marked</code> is <code>TRUE</code> ;</li>
<li>return <code>Y</code> vector.</li>
</ol>
</div>
</div>
</div>
<div id="build-the-model" class="section level2">
<h2 class="hasAnchor">
<a href="#build-the-model" class="anchor"></a>Build the model</h2>
<p>The code below is very usual. For more information, you can look at the documentation of <code>xgboost</code> function (or at the vignette <a href="https://github.com/dmlc/xgboost/blob/master/R-package/vignettes/xgboostPresentation.Rmd">Xgboost presentation</a>).</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1">bst &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xgb.train.html">xgboost</a></span>(<span class="dt">data =</span> sparse_matrix, <span class="dt">label =</span> output_vector, <span class="dt">max_depth =</span> <span class="dv">4</span>,</a>
<a class="sourceLine" id="cb17-2" data-line-number="2">               <span class="dt">eta =</span> <span class="dv">1</span>, <span class="dt">nthread =</span> <span class="dv">2</span>, <span class="dt">nrounds =</span> <span class="dv">10</span>,<span class="dt">objective =</span> <span class="st">"binary:logistic"</span>)</a></code></pre></div>
<pre><code>## [1]  train-error:0.202381 
## [2]  train-error:0.166667 
## [3]  train-error:0.166667 
## [4]  train-error:0.166667 
## [5]  train-error:0.154762 
## [6]  train-error:0.154762 
## [7]  train-error:0.154762 
## [8]  train-error:0.166667 
## [9]  train-error:0.166667 
## [10] train-error:0.166667</code></pre>
<p>You can see some <code>train-error: 0.XXXXX</code> lines followed by a number. It decreases. Each line shows how well the model explains your data. Lower is better.</p>
<p>A model which fits too well may <a href="http://en.wikipedia.org/wiki/Overfitting">overfit</a> (meaning it copy/paste too much the past, and won’t be that good to predict the future).</p>
<blockquote>
<p>Here you can see the numbers decrease until line 7 and then increase.</p>
<p>It probably means we are overfitting. To fix that I should reduce the number of rounds to <code>nrounds = 4</code>. I will let things like that because I don’t really care for the purpose of this example :-)</p>
</blockquote>
</div>
<div id="feature-importance" class="section level2">
<h2 class="hasAnchor">
<a href="#feature-importance" class="anchor"></a>Feature importance</h2>
</div>
<div id="measure-feature-importance" class="section level2">
<h2 class="hasAnchor">
<a href="#measure-feature-importance" class="anchor"></a>Measure feature importance</h2>
<div id="build-the-feature-importance-data-table" class="section level3">
<h3 class="hasAnchor">
<a href="#build-the-feature-importance-data-table" class="anchor"></a>Build the feature importance data.table</h3>
<p>Remember, each binary column corresponds to a single value of one of <em>categorical</em> features.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1">importance &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xgb.importance.html">xgb.importance</a></span>(<span class="dt">feature_names =</span> <span class="kw"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span>(sparse_matrix), <span class="dt">model =</span> bst)</a>
<a class="sourceLine" id="cb19-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(importance)</a></code></pre></div>
<pre><code>##             Feature        Gain      Cover  Frequency
## 1:              Age 0.622031801 0.67251700 0.67241379
## 2: TreatmentTreated 0.285750512 0.11916649 0.10344828
## 3:          SexMale 0.048744021 0.04522027 0.08620690
## 4:      AgeDiscret6 0.016604635 0.04784639 0.05172414
## 5:      AgeDiscret3 0.016373781 0.08028950 0.05172414
## 6:      AgeDiscret4 0.009270557 0.02858800 0.01724138</code></pre>
<blockquote>
<p>The column <code>Gain</code> provide the information we are looking for.</p>
<p>As you can see, features are classified by <code>Gain</code>.</p>
</blockquote>
<p><code>Gain</code> is the improvement in accuracy brought by a feature to the branches it is on. The idea is that before adding a new split on a feature X to the branch there was some wrongly classified elements, after adding the split on this feature, there are two new branches, and each of these branch is more accurate (one branch saying if your observation is on this branch then it should be classified as <code>1</code>, and the other branch saying the exact opposite).</p>
<p><code>Cover</code> measures the relative quantity of observations concerned by a feature.</p>
<p><code>Frequency</code> is a simpler way to measure the <code>Gain</code>. It just counts the number of times a feature is used in all generated trees. You should not use it (unless you know why you want to use it).</p>
<div id="improvement-in-the-interpretability-of-feature-importance-data-table" class="section level4">
<h4 class="hasAnchor">
<a href="#improvement-in-the-interpretability-of-feature-importance-data-table" class="anchor"></a>Improvement in the interpretability of feature importance data.table</h4>
<p>We can go deeper in the analysis of the model. In the <code>data.table</code> above, we have discovered which features counts to predict if the illness will go or not. But we don’t yet know the role of these features. For instance, one of the question we may want to answer would be: does receiving a placebo treatment helps to recover from the illness?</p>
<p>One simple solution is to count the co-occurrences of a feature and a class of the classification.</p>
<p>For that purpose we will execute the same function as above but using two more parameters, <code>data</code> and <code>label</code>.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1">importanceRaw &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xgb.importance.html">xgb.importance</a></span>(<span class="dt">feature_names =</span> <span class="kw"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span>(sparse_matrix), <span class="dt">model =</span> bst, <span class="dt">data =</span> sparse_matrix, <span class="dt">label =</span> output_vector)</a></code></pre></div>
<pre><code>## Warning in xgb.importance(feature_names = colnames(sparse_matrix), model =
## bst, : xgb.importance: parameters 'data', 'label' and 'target' are deprecated</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="co"># Cleaning for better display</span></a>
<a class="sourceLine" id="cb23-2" data-line-number="2">importanceClean &lt;-<span class="st"> </span>importanceRaw[,<span class="st">`</span><span class="dt">:=</span><span class="st">`</span>(<span class="dt">Cover=</span><span class="ot">NULL</span>, <span class="dt">Frequency=</span><span class="ot">NULL</span>)]</a>
<a class="sourceLine" id="cb23-3" data-line-number="3"></a>
<a class="sourceLine" id="cb23-4" data-line-number="4"><span class="kw"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(importanceClean)</a></code></pre></div>
<pre><code>##             Feature        Gain
## 1:              Age 0.622031801
## 2: TreatmentTreated 0.285750512
## 3:          SexMale 0.048744021
## 4:      AgeDiscret6 0.016604635
## 5:      AgeDiscret3 0.016373781
## 6:      AgeDiscret4 0.009270557</code></pre>
<blockquote>
<p>In the table above we have removed two not needed columns and select only the first lines.</p>
</blockquote>
<p>First thing you notice is the new column <code>Split</code>. It is the split applied to the feature on a branch of one of the tree. Each split is present, therefore a feature can appear several times in this table. Here we can see the feature <code>Age</code> is used several times with different splits.</p>
<p>How the split is applied to count the co-occurrences? It is always <code><a href="https://rdrr.io/r/base/Comparison.html">&lt;</a></code>. For instance, in the second line, we measure the number of persons under 61.5 years with the illness gone after the treatment.</p>
<p>The two other new columns are <code>RealCover</code> and <code>RealCover %</code>. In the first column it measures the number of observations in the dataset where the split is respected and the label marked as <code>1</code>. The second column is the percentage of the whole population that <code>RealCover</code> represents.</p>
<p>Therefore, according to our findings, getting a placebo doesn’t seem to help but being younger than 61 years may help (seems logic).</p>
<blockquote>
<p>You may wonder how to interpret the <code>&lt; 1.00001</code> on the first line. Basically, in a sparse <code>Matrix</code>, there is no <code>0</code>, therefore, looking for one hot-encoded categorical observations validating the rule <code>&lt; 1.00001</code> is like just looking for <code>1</code> for this feature.</p>
</blockquote>
</div>
</div>
<div id="plotting-the-feature-importance" class="section level3">
<h3 class="hasAnchor">
<a href="#plotting-the-feature-importance" class="anchor"></a>Plotting the feature importance</h3>
<p>All these things are nice, but it would be even better to plot the results.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="kw"><a href="../reference/xgb.plot.importance.html">xgb.plot.importance</a></span>(<span class="dt">importance_matrix =</span> importance)</a></code></pre></div>
<p><img src="discoverYourData_files/figure-html/unnamed-chunk-13-1.png" width="768" style="display: block; margin: auto;"></p>
<p>Feature have automatically been divided in 2 clusters: the interesting features… and the others.</p>
<blockquote>
<p>Depending of the dataset and the learning parameters you may have more than two clusters. Default value is to limit them to <code>10</code>, but you can increase this limit. Look at the function documentation for more information.</p>
</blockquote>
<p>According to the plot above, the most important features in this dataset to predict if the treatment will work are :</p>
<ul>
<li>the Age ;</li>
<li>having received a placebo or not ;</li>
<li>the sex is third but already included in the not interesting features group ;</li>
<li>then we see our generated features (AgeDiscret). We can see that their contribution is very low.</li>
</ul>
</div>
<div id="do-these-results-make-sense" class="section level3">
<h3 class="hasAnchor">
<a href="#do-these-results-make-sense" class="anchor"></a>Do these results make sense?</h3>
<p>Let’s check some <strong>Chi2</strong> between each of these features and the label.</p>
<p>Higher <strong>Chi2</strong> means better correlation.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1">c2 &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span>(df<span class="op">$</span>Age, output_vector)</a>
<a class="sourceLine" id="cb26-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(c2)</a></code></pre></div>
<pre><code>## 
##  Pearson's Chi-squared test
## 
## data:  df$Age and output_vector
## X-squared = 35.475, df = 35, p-value = 0.4458</code></pre>
<p>Pearson correlation between Age and illness disappearing is <strong>35.48</strong>.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1">c2 &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span>(df<span class="op">$</span>AgeDiscret, output_vector)</a>
<a class="sourceLine" id="cb28-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(c2)</a></code></pre></div>
<pre><code>## 
##  Pearson's Chi-squared test
## 
## data:  df$AgeDiscret and output_vector
## X-squared = 8.2554, df = 5, p-value = 0.1427</code></pre>
<p>Our first simplification of Age gives a Pearson correlation is <strong>8.26</strong>.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1">c2 &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span>(df<span class="op">$</span>AgeCat, output_vector)</a>
<a class="sourceLine" id="cb30-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(c2)</a></code></pre></div>
<pre><code>## 
##  Pearson's Chi-squared test with Yates' continuity correction
## 
## data:  df$AgeCat and output_vector
## X-squared = 2.3571, df = 1, p-value = 0.1247</code></pre>
<p>The perfectly random split I did between young and old at 30 years old have a low correlation of <strong>2.36</strong>. It’s a result we may expect as may be in my mind &gt; 30 years is being old (I am 32 and starting feeling old, this may explain that), but for the illness we are studying, the age to be vulnerable is not the same.</p>
<p>Morality: don’t let your <em>gut</em> lower the quality of your model.</p>
<p>In <em>data science</em> expression, there is the word <em>science</em> :-)</p>
</div>
</div>
<div id="conclusion" class="section level2">
<h2 class="hasAnchor">
<a href="#conclusion" class="anchor"></a>Conclusion</h2>
<p>As you can see, in general <em>destroying information by simplifying it won’t improve your model</em>. <strong>Chi2</strong> just demonstrates that.</p>
<p>But in more complex cases, creating a new feature based on existing one which makes link with the outcome more obvious may help the algorithm and improve the model.</p>
<p>The case studied here is not enough complex to show that. Check <a href="http://www.kaggle.com/">Kaggle website</a> for some challenging datasets. However it’s almost always worse when you add some arbitrary rules.</p>
<p>Moreover, you can notice that even if we have added some not useful new features highly correlated with other features, the boosting tree algorithm have been able to choose the best one, which in this case is the Age.</p>
<p>Linear model may not be that smart in this scenario.</p>
</div>
<div id="special-note-what-about-random-forests" class="section level2">
<h2 class="hasAnchor">
<a href="#special-note-what-about-random-forests" class="anchor"></a>Special Note: What about Random Forests™?</h2>
<p>As you may know, <a href="http://en.wikipedia.org/wiki/Random_forest">Random Forests™</a> algorithm is cousin with boosting and both are part of the <a href="http://en.wikipedia.org/wiki/Ensemble_learning">ensemble learning</a> family.</p>
<p>Both trains several decision trees for one dataset. The <em>main</em> difference is that in Random Forests™, trees are independent and in boosting, the tree <code>N+1</code> focus its learning on the loss (&lt;=&gt; what has not been well modeled by the tree <code>N</code>).</p>
<p>This difference have an impact on a corner case in feature importance analysis: the <em>correlated features</em>.</p>
<p>Imagine two features perfectly correlated, feature <code>A</code> and feature <code>B</code>. For one specific tree, if the algorithm needs one of them, it will choose randomly (true in both boosting and Random Forests™).</p>
<p>However, in Random Forests™ this random choice will be done for each tree, because each tree is independent from the others. Therefore, approximatively, depending of your parameters, 50% of the trees will choose feature <code>A</code> and the other 50% will choose feature <code>B</code>. So the <em>importance</em> of the information contained in <code>A</code> and <code>B</code> (which is the same, because they are perfectly correlated) is diluted in <code>A</code> and <code>B</code>. So you won’t easily know this information is important to predict what you want to predict! It is even worse when you have 10 correlated features…</p>
<p>In boosting, when a specific link between feature and outcome have been learned by the algorithm, it will try to not refocus on it (in theory it is what happens, reality is not always that simple). Therefore, all the importance will be on feature <code>A</code> or on feature <code>B</code> (but not both). You will know that one feature have an important role in the link between the observations and the label. It is still up to you to search for the correlated features to the one detected as important if you need to know all of them.</p>
<p>If you want to try Random Forests™ algorithm, you can tweak Xgboost parameters!</p>
<p>For instance, to compute a model with 1000 trees, with a 0.5 factor on sampling rows and columns:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(agaricus.train, <span class="dt">package=</span><span class="st">'xgboost'</span>)</a>
<a class="sourceLine" id="cb32-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(agaricus.test, <span class="dt">package=</span><span class="st">'xgboost'</span>)</a>
<a class="sourceLine" id="cb32-3" data-line-number="3">train &lt;-<span class="st"> </span>agaricus.train</a>
<a class="sourceLine" id="cb32-4" data-line-number="4">test &lt;-<span class="st"> </span>agaricus.test</a>
<a class="sourceLine" id="cb32-5" data-line-number="5"></a>
<a class="sourceLine" id="cb32-6" data-line-number="6"><span class="co">#Random Forest™ - 1000 trees</span></a>
<a class="sourceLine" id="cb32-7" data-line-number="7">bst &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xgb.train.html">xgboost</a></span>(<span class="dt">data =</span> train<span class="op">$</span>data, <span class="dt">label =</span> train<span class="op">$</span>label, <span class="dt">max_depth =</span> <span class="dv">4</span>, <span class="dt">num_parallel_tree =</span> <span class="dv">1000</span>, <span class="dt">subsample =</span> <span class="fl">0.5</span>, <span class="dt">colsample_bytree =</span><span class="fl">0.5</span>, <span class="dt">nrounds =</span> <span class="dv">1</span>, <span class="dt">objective =</span> <span class="st">"binary:logistic"</span>)</a></code></pre></div>
<pre><code>## [1]  train-error:0.001689</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1"><span class="co">#Boosting - 3 rounds</span></a>
<a class="sourceLine" id="cb34-2" data-line-number="2">bst &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xgb.train.html">xgboost</a></span>(<span class="dt">data =</span> train<span class="op">$</span>data, <span class="dt">label =</span> train<span class="op">$</span>label, <span class="dt">max_depth =</span> <span class="dv">4</span>, <span class="dt">nrounds =</span> <span class="dv">3</span>, <span class="dt">objective =</span> <span class="st">"binary:logistic"</span>)</a></code></pre></div>
<pre><code>## [1]  train-error:0.006142 
## [2]  train-error:0.006756 
## [3]  train-error:0.001228</code></pre>
<blockquote>
<p>Note that the parameter <code>round</code> is set to <code>1</code>.</p>
</blockquote>
<blockquote>
<p><a href="https://www.stat.berkeley.edu/~breiman/RandomForests/cc_papers.htm"><strong>Random Forests™</strong></a> is a trademark of Leo Breiman and Adele Cutler and is licensed exclusively to Salford Systems for the commercial release of the software.</p>
</blockquote>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">

        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li>
<a href="#understand-your-dataset-with-xgboost">Understand your dataset with XGBoost</a><ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">Introduction</a></li>
      <li><a href="#preparation-of-the-dataset">Preparation of the dataset</a></li>
      <li><a href="#build-the-model">Build the model</a></li>
      <li><a href="#feature-importance">Feature importance</a></li>
      <li><a href="#measure-feature-importance">Measure feature importance</a></li>
      <li><a href="#conclusion">Conclusion</a></li>
      <li><a href="#special-note-what-about-random-forests">Special Note: What about Random Forests™?</a></li>
      </ul>
</li>
      </ul>
</div>
      </div>

</div>



      <footer><div class="copyright">
  <p>Developed by Tianqi Chen, Tong He, Michael Benesty, Vadim Khotilovich, Yuan Tang, Hyunsu Cho, Kailong Chen, Rory Mitchell, Ignacio Cano, Tianyi Zhou, Mu Li, Junyuan Xie, Min Lin, Yifeng Geng, Yutian Li.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
